name: crypto
description: Crypto app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  core:
    path: packages/core
  dio: ^5.7.0
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
