name: api
description: General client to manage http request
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
